{
 "title": "FastAPI RED",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(fastapi_requests_total{}[$__rate_interval])",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Request Error",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(fastapi_responses_total{status_code!~\"2.*|3.*\"}) by(path) or sum(fastapi_responses_total{}) by (path) * 0) / sum(fastapi_responses_total{}) by (path)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, path) (rate(fastapi_requests_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "PR95 {{path}}"
    }
   ]
  }
 ]
}