{
 "title": "Grafana Stats",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(grafana_build_info,job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Main Infomation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"$job\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Organization Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_total_orgs{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_total_users{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dashboards Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_totals_dashboard{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Source Count",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_totals_datasource{job=\"$job\"}",
     "legendFormat": "{{plugin_id}}"
    }
   ]
  },
  {
   "title": "Grafana Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_build_info{job=\"$job\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "User and system CPU time spent in seconds.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$job\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Virtual and Resident memory size in bytes, over 5 min interval",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{job=\"$job\"}[5m])",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "rate(process_virtual_memory_bytes{job=\"$job\"}[5m])",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "process_open_fds{job=\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Responce Codes and Logins", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Total Response Statuses",
   "type": "timeseries",
   "description": "http response status",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "grafana_api_response_status_total{job=\"$job\"}",
     "legendFormat": "API {{code}}"
    },
    {
     "expr": "grafana_page_response_status_total{job=\"$job\"}",
     "legendFormat": "Page {{code}}"
    },
    {
     "expr": "grafana_proxy_response_status_total{job=\"$job\"}",
     "legendFormat": "Proxy {{code}}"
    }
   ]
  },
  {
   "title": "Login Counts",
   "type": "timeseries",
   "description": "api login counters",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "grafana_api_login_post_total{job=\"$job\"}",
     "legendFormat": "Post"
    },
    {
     "expr": "grafana_api_login_oauth_total{job=\"$job\"}",
     "legendFormat": "OAuth"
    }
   ]
  }
 ]
}