{
 "title": "Frontend Observability",
 "description": "Frontend monitoring dashboard using metrics collected with Grafana Faro SDK.",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "Application",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TTFB (Time to First Byte)",
   "type": "stat",
   "description": "TTFB is a metric that measures the time between the request for a resource and when the first byte of a response begins to arrive.\nhttps://web.dev/ttfb/",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time({service=\"$app\"} |= \"ttfb\" | logfmt | kind=\"measurement\" | unwrap ttfb [$__range]) by (app_name)",
     "legendFormat": "{{app_name}}"
    }
   ]
  },
  {
   "title": "FCP (First Contentful Paint)",
   "type": "stat",
   "description": "The First Contentful Paint (FCP) metric measures the time from when the page starts loading to when any part of the page's content is rendered on the screen. For this metric, \"content\" refers to text, images (including background images), <svg> elements, or non-white <canvas> elements.\nhttps://web.dev/fcp/",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time({service=\"$app\"} |= \" fcp=\" | logfmt | kind=\"measurement\" | unwrap fcp [$__range]) by (app_name)",
     "legendFormat": "{{app_name}}"
    }
   ]
  },
  {
   "title": "LCP (Largest Contentful Paint)",
   "type": "stat",
   "description": "Largest Contentful Paint (LCP): measures loading performance. To provide a good user experience, LCP should occur within 2.5 seconds of when the page first starts loading.\nhttps://web.dev/lcp/",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time({service=\"$app\"} |= \" lcp=\" | logfmt | kind=\"measurement\" | unwrap lcp [$__range]) by (app_name)",
     "legendFormat": "{{app_name}}"
    }
   ]
  },
  {
   "title": "CLS (Cumulative Layout Shift)",
   "type": "stat",
   "description": "Cumulative Layout Shift (CLS): measures visual stability. To provide a good user experience, pages should maintain a CLS of 0.1. or less.\nhttps://web.dev/cls/",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time({service=\"$app\"} |= \"cls\" | logfmt | kind=\"measurement\" | unwrap cls [$__range]) by (app_name)",
     "legendFormat": "{{app_name}}"
    }
   ]
  },
  {
   "title": "FID (First Input Delay)",
   "type": "stat",
   "description": "First Input Delay (FID): measures interactivity. To provide a good user experience, pages should have a FID of 100 milliseconds or less.\nhttps://web.dev/fid/",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time({service=\"$app\"} |= \" fid=\" | logfmt | kind=\"measurement\" | unwrap fid [$__range]) by (app_name)",
     "legendFormat": "{{app_name}}"
    }
   ]
  },
  {
   "title": "INP (Interaction to Next Paint)",
   "type": "stat",
   "description": "Interaction to Next Paint (INP): measures interactivity. To provide a good user experience, pages should have a INP of 200 milliseconds or less.\nhttps://web.dev/fid/",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time({service=\"$app\"} |= \" inp=\" | logfmt | kind=\"measurement\" | unwrap inp [$__range]) by (app_name)",
     "legendFormat": "{{app_name}}"
    }
   ]
  },
  {
   "title": "Page Load, p75",
   "type": "timeseries",
   "description": "TTFB is a metric that measures the time between the request for a resource and when the first byte of a response begins to arrive.\nhttps://web.dev/ttfb/",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.75, {service=\"$app\"} |= \" ttfb=\" | logfmt | kind=\"measurement\" | unwrap ttfb [5m]) by (app_name)",
     "legendFormat": "TTFB - {{app_name}}"
    },
    {
     "expr": "quantile_over_time(0.75, {service=\"$app\"} |= \" fcp=\" | logfmt | kind=\"measurement\" | unwrap fcp [5m]) by (app_name)",
     "legendFormat": "FCP - {{app_name}}"
    },
    {
     "expr": "quantile_over_time(0.75, {service=\"$app\"} |= \" lcp=\" | logfmt | kind=\"measurement\" | unwrap lcp [5m]) by (app_name)",
     "legendFormat": "LCP - {{app_name}}"
    }
   ]
  },
  {
   "title": "Cumulative Layout Shift, p75",
   "type": "timeseries",
   "description": "Cumulative Layout Shift (CLS): measures visual stability. To provide a good user experience, pages should maintain a CLS of 0.1. or less.\nhttps://web.dev/cls/",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "targets": [
    {
     "expr": "quantile_over_time(0.75, {service=\"$app\"} |= \" cls=\" | logfmt | kind=\"measurement\" | unwrap cls [5m]) by (app_name)",
     "legendFormat": "CLS - {{app_name}}"
    }
   ]
  },
  {
   "title": "Input Response time, p75",
   "type": "timeseries",
   "description": "First Input Delay (FID): measures interactivity. To provide a good user experience, pages should have a FID of 100 milliseconds or less.\nhttps://web.dev/fid/",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.75, {service=\"$app\"} |= \" fid=\" | logfmt | kind=\"measurement\" | unwrap fid [5m]) by (app_name)",
     "legendFormat": "FID - {{app_name}}"
    },
    {
     "expr": "quantile_over_time(0.75, {service=\"$app\"} |= \" inp=\" | logfmt | kind=\"measurement\" | unwrap inp [5m]) by (app_name)",
     "legendFormat": "INP - {{app_name}}"
    }
   ]
  },
  { "title": "Exceptions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({service=\"$app\"} | logfmt | kind=\"exception\" [$__range])) by (app_name)",
     "legendFormat": "{{app_name}}"
    }
   ]
  },
  {
   "title": "Exceptions Over Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 13 },
   "targets": [
    {
     "expr": "count_over_time({service=\"$app\"} | logfmt  | kind=\"exception\" [$__interval])",
     "legendFormat": "{{app_name}}"
    }
   ]
  },
  {
   "title": "Top Exceptions",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "topk(10, count(count_over_time({service=\"$app\"} | logfmt | kind=\"exception\" [$__range])) by (value, app_name))"
    }
   ]
  },
  {
   "title": "Top URLs by Exception Count",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "topk(10, count(count_over_time({service=\"$app\"} | logfmt | kind=\"exception\" [$__range])) by (page_url, app_name))"
    }
   ]
  },
  {
   "title": "Top Browsers by Exception Count",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "topk(10, count by (browser_name, browser_version, app_name) (count_over_time({service=\"$app\"} | logfmt [$__range])))"
    }
   ]
  },
  { "title": "Meta", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Popular Browsers",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "topk(10, count(count_over_time({service=\"$app\"} |= \" ttfb=\" | logfmt | kind=\"measurement\" [$__range])) by (browser_name, browser_version, app_name))"
    }
   ]
  },
  {
   "title": "Visits",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "count_over_time({service=\"$app\"} |= \" ttfb=\" | logfmt | kind=\"measurement\" [$__interval])",
     "legendFormat": "{{app_name}}"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Top Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "topk(10, count(count_over_time({service=\"$app\"} | logfmt | kind=\"event\" [$__range])) by (event_name, app_name))"
    }
   ]
  },
  {
   "title": "Top Users",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "topk(50, count(count_over_time({service=\"$app\"} | logfmt | event_name = \"mainspa_mount\" | kind=\"measurement\" [$__range])) by (user_id))"
    }
   ]
  }
 ]
}